# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm86750-ping

on:
  push:
    branches:
      - aula
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_11c8d7da7ec54b71acefc91afe22de7c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5bee323cd5e9424ea5965ef867ce5c12 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_11c8d7da7ec54b71acefc91afe22de7c }}/ping:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm86750-ping'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e8a98ed114145aba06c589d5c0df7a3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_11c8d7da7ec54b71acefc91afe22de7c }}/ping:${{ github.sha }}'